### PR TITLE
Create frontend to connect to MIR nodes to accept or decline new logs

### PR DESCRIPTION
**Pull request by andreaj00**
Create frontend to connect to MIR nodes to accept or decline new logs. See attached images for examples.

The MIR nodes should run on port 8080+<membership number>

Use cases:
1) Connecting to non-existing ws port
image

2) Connecting to existing ws port and starting to receive log messages
image

3) Clicking on 'Decline' -> decline the incoming log message and receive the new log message
image

4) Clicking on 'Accept' -> accept the incoming log message and store it in "Accepted Logs" and receive the new log message
image

### CODE REVIEW

**Comment by matejpavlovic** [comment]
Thanks @andreaj00 for the commit and sorry for the long delay in responding.
LGTM, as far as I can read Javascript and React (very little).

Is the code in this PR already usable? Is the websocket interceptor already there, such that opening this web page and connecting to a Mir node already works, or does that depend on @Cath3876 's PR (which is not merged yet)?

**Comment by andreaj00** [comment]
Hi @matejpavlovic,

No worries :)

This commit addresses only the frontend part. Therefore, it assumes that a MIR node's websocket is running when attempting to connect to a given port; otherwise, it will throw an error message. 
Checking the current status of the visualization branch, it doesn't seem like that functionality is there yet. So, for now, it can probably only replicate case 1 and not 2/3/4.

**Comment by matejpavlovic** [comment]
Ah I see. In that case, let's not merge this before the backend gets merged. What you can already do, however, is continuing to work on top of this branch and submit further PRs with new branches that extend it. Once @Cath3876 's PR is ready and merged, we'll merge these as well.

In case there is not too much left to do on the frontend/javascript side, you can make a PR with a .md file containing the specification of the interface between the backend and the frontend.

**Comment by andreaj00** [comment]
Great! That sounds good, I will do it in the following weeks :)

**Pull request merged**
